FROM python:3.12

WORKDIR /app/src/backend

COPY . .

RUN pip install --upgrade pip && pip install -r requirements.txt

ENV C_FORCE_ROOT=1



ENTRYPOINT ["celery", "-A", "internal.tasks:cel", "worker", "--loglevel=info", "--pool=solo"]
