version: '3.8'

services:
  backend:
    build:
      context: ./backend
    networks:
      app-network:
        ipv4_address: 172.21.0.2

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      app-network:
        ipv4_address: 172.21.0.3
    volumes:
      - frontend-build:/usr/share/nginx/html


networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24

volumes:
  frontend-build: