version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    networks:
      app-network:
        ipv4_address: 172.21.0.2

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    networks:
      app-network:
        ipv4_address: 172.21.0.3
    volumes:
      - frontend-build:/app/build

  nginx:
    build:
      context: .
    ports:
      - "80:80"
    networks:
      app-network:
        ipv4_address: 172.21.0.4
    depends_on:
      - frontend


networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24

volumes:
  frontend-build:
