version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    networks:
      app-network:
        ipv4_address: 172.21.0.2


  nginx:
    container_name: nginx
    build:
      context: .
    ports:
      - "80:80"
    networks:
      app-network:
        ipv4_address: 172.21.0.4
    depends_on:
      - frontend

  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: dbpostgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      app-network:
        ipv4_address: 172.21.0.5

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24

volumes:
  frontend-build:
