version: '3.8'

services:
  backend:
    build:
      context: ./backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    networks:
      - app-network


  nginx:
    build:
      context: .
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - frontend
    volumes:
      - ./frontend/build:/usr/share/nginx/html

networks:
  app-network:
    driver: bridge

